//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premium_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cyclus_DataEntities : DbContext
    {
        public Cyclus_DataEntities()
            : base("name=Cyclus_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Instellingen_Periodes> tbl_Instellingen_Periodes { get; set; }
        public virtual DbSet<tbl_Medewerkers> tbl_Medewerkers { get; set; }
        public virtual DbSet<tbl_Medewerkers_Info> tbl_Medewerkers_Info { get; set; }
        public virtual DbSet<tbl_Medewerkers_Uren> tbl_Medewerkers_Uren { get; set; }
        public virtual DbSet<tbl_Medewerkers_Urencodes> tbl_Medewerkers_Urencodes { get; set; }
        public virtual DbSet<tbl_Medewerkers_Weken> tbl_Medewerkers_Weken { get; set; }
    }
}
