//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premium_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Medewerkers_Info
    {
        public int VOLGNUMMER { get; set; }
        public string MEDEWERKER_ID { get; set; }
        public string MEDEWERKER_NAAM { get; set; }
        public string AFDELING { get; set; }
        public string FUNCTIENAAM { get; set; }
        public string MANAGER_NAAM { get; set; }
        public string VOORKEUR_OVERUREN { get; set; }
        public string JAAR_VORIG { get; set; }
        public string JAAR_HUIDIG { get; set; }
        public Nullable<System.DateTime> BIJGEWERKT_TOT_DATUM { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_BASIS_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_BOVENWETTELIJK_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_ADV_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_COMPENSATIE_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_TEGOED_INHAALUREN_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_TEGOED_VERLOF_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_BIJGEKOCHT_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_AFWIJKEND_VORIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_1_VORIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_2_VORIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_3_VORIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_4_VORIG_JAAR { get; set; }
        public Nullable<decimal> ADV_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> TVT_OPGEBOUWD_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> TVT_OPGENOMEN_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> TVT_UITBETAALD_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> TVT_SALDO_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPGEBOUWD_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPGENOMEN_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_SALDO_TOTAAL_VORIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_BASIS_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_BOVENWETTELIJK_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_ADV_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_COMPENSATIE_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_TEGOED_INHAALUREN_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_TEGOED_VERLOF_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_BIJGEKOCHT_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPBOUW_AFWIJKEND_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_1_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_2_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_3_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> ADV_KWARTAAL_4_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> ADV_TOTAAL_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> TVT_OPGEBOUWD_TOTAAL_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> TVT_OPGENOMEN_TOTAAL_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> TVT_UITBETAALD_TOTAAL_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> TVT_SALDO_TOTAAL_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPGEBOUWD_TOTAAL_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_OPGENOMEN_TOTAAL_HUIDIG_JAAR { get; set; }
        public Nullable<decimal> VERLOF_SALDO_TOTAAL_HUIDIG_JAAR { get; set; }
        public string BESTAND_01 { get; set; }
        public string BESTAND_02 { get; set; }
        public string OPMERKINGEN { get; set; }
        public Nullable<System.DateTime> INGEVOERD_DATUM { get; set; }
        public string INGEVOERD_NAAM { get; set; }
        public string INGEVOERD_COMPUTER { get; set; }
        public Nullable<System.TimeSpan> INGEVOERD_TIJD { get; set; }
        public Nullable<bool> INGEVOERD_CHECK { get; set; }
        public Nullable<System.DateTime> GEWIJZIGD_DATUM { get; set; }
        public string GEWIJZIGD_NAAM { get; set; }
        public string GEWIJZIGD_COMPUTER { get; set; }
        public Nullable<System.TimeSpan> GEWIJZIGD_TIJD { get; set; }
        public Nullable<bool> GEWIJZIGD_CHECK { get; set; }
        public Nullable<bool> CHECKED { get; set; }
        public Nullable<bool> VERWIJDEREN { get; set; }
        public string INDEX { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
