//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premium_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Medewerkers_Urencodes
    {
        public int VOLGNUMMER { get; set; }
        public string MEDEWERKER_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public string PROJECT_NAAM { get; set; }
        public string OPMERKINGEN { get; set; }
        public Nullable<System.DateTime> INGEVOERD_DATUM { get; set; }
        public string INGEVOERD_NAAM { get; set; }
        public string INGEVOERD_COMPUTER { get; set; }
        public Nullable<System.TimeSpan> INGEVOERD_TIJD { get; set; }
        public Nullable<bool> INGEVOERD_CHECK { get; set; }
        public Nullable<System.DateTime> GEWIJZIGD_DATUM { get; set; }
        public string GEWIJZIGD_NAAM { get; set; }
        public string GEWIJZIGD_COMPUTER { get; set; }
        public Nullable<System.TimeSpan> GEWIJZIGD_TIJD { get; set; }
        public Nullable<bool> GEWIJZIGD_CHECK { get; set; }
        public Nullable<bool> CHECKED { get; set; }
        public Nullable<bool> VERWIJDEREN { get; set; }
        public string INDEX { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
