//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premium_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Medewerkers_Uren
    {
        public int VOLGNUMMER { get; set; }
        public string MEDEWERKER_ID { get; set; }
        public string MEDEWERKER_NAAM { get; set; }
        public string MEDEWERKER_ORGANISATIE { get; set; }
        public string MANAGER_ID { get; set; }
        public string MANAGER_NAAM { get; set; }
        public string JAAR { get; set; }
        public string RECORD_STATUS { get; set; }
        public string MEDEWERKER_TYPE { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> DATUM { get; set; }
        public Nullable<System.DateTime> DAG { get; set; }
        public string PERIODE_WEEK { get; set; }
        public Nullable<decimal> START { get; set; }
        public Nullable<decimal> EINDE { get; set; }
        public Nullable<decimal> UREN { get; set; }
        public Nullable<bool> OVERUREN_CHECK { get; set; }
        public Nullable<decimal> UREN_NORMAAL { get; set; }
        public Nullable<decimal> UREN_OVERUREN { get; set; }
        public string PROJECT_ID { get; set; }
        public string PROJECT_NAAM { get; set; }
        public string OPMERKINGEN { get; set; }
        public Nullable<decimal> OVERUREN_UITBETALEN { get; set; }
        public string HERKOMST { get; set; }
        public string VOLGORDE { get; set; }
        public Nullable<System.DateTime> INGEVOERD_DATUM { get; set; }
        public string INGEVOERD_NAAM { get; set; }
        public Nullable<System.TimeSpan> INGEVOERD_TIJD { get; set; }
        public Nullable<bool> INGEVOERD_CHECK { get; set; }
        public Nullable<System.DateTime> GEWIJZIGD_DATUM { get; set; }
        public string GEWIJZIGD_NAAM { get; set; }
        public Nullable<System.TimeSpan> GEWIJZIGD_TIJD { get; set; }
        public Nullable<bool> GEWIJZIGD_CHECK { get; set; }
        public Nullable<bool> CHECKED { get; set; }
        public Nullable<bool> VERWIJDEREN { get; set; }
        public string INDEX { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
