//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premium_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Medewerkers
    {
        public int VOLGNUMMER { get; set; }
        public string MEDEWERKER_ID { get; set; }
        public string MEDEWERKER_STATUS { get; set; }
        public string MEDEWERKER_TYPE { get; set; }
        public string MEDEWERKER_ORGANISATIE { get; set; }
        public Nullable<System.DateTime> DATUM_IN_DIENST { get; set; }
        public Nullable<System.DateTime> DATUM_UIT_DIENST { get; set; }
        public string MEDEWERKER_NAAM { get; set; }
        public string VOORLETTERS { get; set; }
        public string VOORNAAM { get; set; }
        public string TUSSENVOEGSEL { get; set; }
        public string ACHTERNAAM { get; set; }
        public string GESLACHT { get; set; }
        public string E_MAILADRES_ZAKELIJK { get; set; }
        public string E_MAILADRES_PRIVE { get; set; }
        public Nullable<System.DateTime> GEBOORTEDATUM { get; set; }
        public string OPMERKINGEN { get; set; }
        public string FUNCTIENAAM { get; set; }
        public Nullable<double> CONTRACTUREN_WEEK { get; set; }
        public string AFDELING { get; set; }
        public string MANAGER { get; set; }
        public string MANAGER_ID { get; set; }
        public string BESTAND_01 { get; set; }
        public string BESTAND_02 { get; set; }
        public Nullable<System.DateTime> INGEVOERD_DATUM { get; set; }
        public string INGEVOERD_NAAM { get; set; }
        public string INGEVOERD_COMPUTER { get; set; }
        public Nullable<System.TimeSpan> INGEVOERD_TIJD { get; set; }
        public Nullable<bool> INGEVOERD_CHECK { get; set; }
        public Nullable<System.DateTime> GEWIJZIGD_DATUM { get; set; }
        public string GEWIJZIGD_NAAM { get; set; }
        public string GEWIJZIGD_COMPUTER { get; set; }
        public Nullable<System.TimeSpan> GEWIJZIGD_TIJD { get; set; }
        public Nullable<bool> GEWIJZIGD_CHECK { get; set; }
        public Nullable<bool> VERREKENEN { get; set; }
        public Nullable<bool> CHECKED { get; set; }
        public string ZOEKVELD { get; set; }
        public Nullable<bool> VERWIJDEREN { get; set; }
        public string INDEX { get; set; }
        public bool INLOG_ACTIEF { get; set; }
        public string INLOG_GEBRUIKERSNAAM { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string INLOG_WACHTWOORD { get; set; }
        public Nullable<int> INLOG_LEVEL { get; set; }
        public bool OVERUREN_SCHRIJVEN { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
