//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Premium_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Medewerkers_Weken
    {
        public int VOLGNUMMER { get; set; }
        public string MEDEWERKER_ID { get; set; }
        public string MEDEWERKER_NAAM { get; set; }
        public string MEDEWERKER_ORGANISATIE { get; set; }
        public string WEEK_STATUS { get; set; }
        public string WEEK_SOORT { get; set; }
        public Nullable<decimal> WEEK_BUDGET { get; set; }
        public string PERIODE_WEEK { get; set; }
        public string JAAR { get; set; }
        public Nullable<decimal> TOTAAL_UREN { get; set; }
        public Nullable<decimal> TOTAAL_OVERUREN { get; set; }
        public Nullable<decimal> TOTAAL_UREN_OVERUREN { get; set; }
        public string MANAGER_ID { get; set; }
        public string MANAGER_NAAM { get; set; }
        public Nullable<bool> GOEDGEKEURD_CHECK { get; set; }
        public Nullable<System.DateTime> GOEDGEKEURD_DATUM { get; set; }
        public string GOEDGEKEURD_NAAM { get; set; }
        public Nullable<System.TimeSpan> GOEDGEKEURD_TIJD { get; set; }
        public string OPMERKINGEN { get; set; }
        public Nullable<System.DateTime> INGEVOERD_DATUM { get; set; }
        public string INGEVOERD_NAAM { get; set; }
        public Nullable<System.TimeSpan> INGEVOERD_TIJD { get; set; }
        public Nullable<System.DateTime> GEWIJZIGD_DATUM { get; set; }
        public string GEWIJZIGD_NAAM { get; set; }
        public Nullable<System.TimeSpan> GEWIJZIGD_TIJD { get; set; }
        public string EMAIL_ONDERWERP { get; set; }
        public Nullable<System.DateTime> EMAIL_DATUM { get; set; }
        public Nullable<System.TimeSpan> EMAIL_TIJD { get; set; }
        public string EMAIL_NAAM { get; set; }
        public Nullable<bool> EMAIL_CHECK { get; set; }
        public Nullable<bool> GEWIJZIGD_CHECK { get; set; }
        public Nullable<bool> CHECKED { get; set; }
        public Nullable<bool> VERWIJDEREN { get; set; }
        public string INDEX { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
